// GarminFoodApp.swift
//
// The app's entry point. Deliberately minimal right now — this file's only
// job is task 6.1 of add-garmin-auth-and-sync: prove that `xcodebuild` can
// build something in CI at all, on a project generated by XcodeGen from
// ios/project.yml, before any Garmin-specific code exists.
//
// No GarminKit, no auth, no widgets yet. Those land as their own tasks.

import SwiftUI

@main
struct GarminFoodApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
